name: json_serializable_helper
description: A builder to generate json_serializable classes from json files.
version: 1.0.1
repository: https://github.com/meysammahfouzi/json_serializable_helper

environment:
  sdk: ^3.1.5

dependencies:
  build: ^2.4.1
  dart_style: ^2.3.4

dev_dependencies:
  test: ^1.16.8
  lints: ^3.0.0
